### ISSUE TITLE
Investment Model needs to be changed

### ISSUE THREAD

**Issue by ritmatter** [krazemon/reps#461]
Right now, are investment platform does not actually make sense. This is because we do not convert reps into another currency, which happens in real life when money is converted into stocks.

But, we can fix this with a new model. Rather than profiting from a sell, an investor should be consistently profiting from dividends. Some questions:

1) How often are dividends given?
2) How are dividend portions calculated?

Here is how the system will work:

When a user invests in an expert, they own a percentile of that expert's reps. This percentile will not change. Daily, a job will go through paying all investors dividends. The dividend is calculated as an investor's percentile at the time of the original investment * dividend rate * total reps for that expert;

Here is what needs to be changed:

1) Unit-tested job that will pay dividends
2) Transaction amounts should now be rounded to the nearest tenth, not integer
3) When revoking an investment, the investor should simply get back the reps invested originally
4) Valuation field should be removed
5) A user making an investment will not make it necessary to update other investors at all

**Comment by krazemon** [comment]
Does updating expert percentiles remain the same? I believe it does.

**Comment by ritmatter** [comment]
I think expert percentiles should remain the same.

**Comment by krazemon** [comment]
Closing this as we, in theory, have fixed this with our dividends update.
