### ISSUE TITLE
updateInvestorPortfolio should not call splice

### ISSUE THREAD

**Issue by ritmatter** [krazemon/reps#473]
It creates an undefined in the array that contributed to the recent revoke bug

**Comment by krazemon** [comment]
I don't think this makes sense.
The point of splice is that it doesn't leave an undefined.

**Comment by krazemon** [comment]
We're going to have to talk about this more, because I'm very confused about how splice could leave an undefined.

**Comment by krazemon** [comment]
Closing.

**Comment by krazemon** [comment]
Per our discussion IRL.
